### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by spwpun** [RFCNLP/RFCNLP#1]
The command I used: `python3 nlp-parser/liner.py --protocol BGPv4 --outdir ./BGPv4`
An IndexError in `RFCNLP/nlp-parser/data_utils_NEW.py", line 695`,

![image](https://user-images.githubusercontent.com/32606457/159894257-cd27b7df-5735-4e70-abeb-938750d8e762.png)

**Comment by maxvonhippel** [comment]
Hey!  Thanks for reporting this.  Sorry I didn't see the alert earlier.  I'll take a look.

**Comment by maxvonhippel** [comment]
I've reproduced the bug.  We're working on fixing it.
```
(base) max@max-XPS-13-9310:~/projects/research/nds2/RFC-NLP/rfc-nlp-anon$ sudo docker run -it rfcnlp bash
root@6849c52ddebc:/workspace/rfcnlp# python3 nlp-parser/linear.py --protocol BGPv4 --outdir ./BGPv4
{'B-TRIGGER': 0, 'I-TRIGGER': 1, 'B-ACTION': 2, 'I-ACTION': 3, 'O': 4, 'B-TRANSITION': 5, 'I-TRANSITION': 6, 'B-VARIABLE': 7, 'I-VARIABLE': 8, 'B-ERROR': 9, 'I-ERROR': 10, 'B-TIMER': 11, 'I-TIMER': 12}
vocabulary size 2236
Iteration 0
dual: 31.685795, dual_gap: 1494.174130, primal: 1525.859925
Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5
Iteration 6
Iteration 7
Iteration 8
Iteration 9
Calculating final objective.
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
              precision    recall  f1-score   support

    B-ACTION     0.0778    0.0473    0.0588       148
     B-ERROR     0.0000    0.0000    0.0000         7
     B-TIMER     0.7500    0.2581    0.3840        93
B-TRANSITION     0.8000    0.9492    0.8682        59
   B-TRIGGER     0.5149    0.9204    0.6603       113
  B-VARIABLE     0.2857    0.8485    0.4275        33
    I-ACTION     0.4721    0.2673    0.3413       823
     I-ERROR     0.1304    0.0400    0.0612        75
     I-TIMER     0.8387    0.1940    0.3152       536
I-TRANSITION     0.6983    0.9535    0.8062       301
   I-TRIGGER     0.6012    0.6907    0.6429      1565
  I-VARIABLE     0.1618    0.7736    0.2677       159
           O     0.7258    0.6746    0.6993      2299

    accuracy                         0.5777      6211
   macro avg     0.4659    0.5090    0.4256      6211
weighted avg     0.6262    0.5777    0.5696      6211

ACC 0.5776847528578328
WEIGHTED f1 0.5695986579526949
MACRO F1 0.42558337684650827
2022-03-28 14:59:17 root INFO: Imported 6 predictions for 6 true examples
ent_type 0.5330812854442344
partial 0.6691871455576559
strict 0.24574669187145556
exact 0.42911153119092627
2022-03-28 14:59:17 root INFO: Imported 6 predictions for 6 true examples
TRIGGER ent_type 0.6788990825688073
TRIGGER partial 0.46177370030581044
TRIGGER strict 0.24464831804281345
TRIGGER exact 0.24464831804281345
2022-03-28 14:59:17 root INFO: Imported 6 predictions for 6 true examples
ACTION ent_type 0.4833333333333334
ACTION partial 0.26666666666666666
ACTION strict 0.05
ACTION exact 0.05
2022-03-28 14:59:17 root INFO: Imported 6 predictions for 6 true examples
ERROR ent_type 0.16666666666666666
ERROR partial 0.08333333333333333
ERROR strict 0.0
ERROR exact 0.0
2022-03-28 14:59:17 root INFO: Imported 6 predictions for 6 true examples
TIMER ent_type 0.448
TIMER partial 0.27999999999999997
TIMER strict 0.112
TIMER exact 0.112
2022-03-28 14:59:17 root INFO: Imported 6 predictions for 6 true examples
TRANSITION ent_type 0.8201438848920863
TRANSITION partial 0.8129496402877698
TRANSITION strict 0.8057553956834532
TRANSITION exact 0.8057553956834532
2022-03-28 14:59:17 root INFO: Imported 6 predictions for 6 true examples
VARIABLE ent_type 0.39160839160839156
VARIABLE partial 0.34265734265734266
VARIABLE strict 0.29370629370629375
VARIABLE exact 0.29370629370629375
False False False False
False False False True
Traceback (most recent call last):
  File "nlp-parser/linear.py", line 167, in <module>
    main()
  File "nlp-parser/linear.py", line 139, in main
    apply_heuristics(X_test_data_alt, y_test_trans_alt, y_pred_trans_alt,
  File "/workspace/rfcnlp/nlp-parser/eval_utils.py", line 62, in apply_heuristics
    data_utils.join_consecutive_transitions(
  File "/workspace/rfcnlp/nlp-parser/data_utils_NEW.py", line 694, in join_consecutive_transitions
    if y_p[i-1][0].endswith('TRANSITION') and y_p[i][0].endswith('TRANSITION') and \
IndexError: list index out of range
root@6849c52ddebc:/workspace/rfcnlp# 
```
