### ISSUE TITLE
make dccplineartrain failed due to dependency issues

### ISSUE THREAD

**Issue by s1awwhy** [RFCNLP/RFCNLP#10]
Hello，I followed the steps in the readme to try to reproduce RFCNLP. After I completed building the docker image, I encountered the following error when making dccplineartrain in the container:
```
root@dose:/workspace/rfcnlp# make dccplineartrain
WANDB_MODE="dryrun" WANRB_API_KEY="dryrun"  \
        python3 nlp-parser/linear.py            \
        --protocol DCCP                         \
        --stem                                  \
        --heuristics                            \
        --phrase_level                          \
        --outdir rfcs-predicted/linear_phrases/ \
        --write_results
/workspace/rfcnlp/nlp-parser/data_utils_NEW.py:354: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return X_train, np.array(y_train), level_h_train, level_d_train
{'B-TRIGGER': 0, 'B-ACTION': 1, 'O': 2, 'B-TRANSITION': 3, 'B-VARIABLE': 4, 'B-ERROR': 5, 'B-TIMER': 6}
/workspace/rfcnlp/nlp-parser/features.py:212: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(X_new)
vocabulary size 1287
Iteration 0
Traceback (most recent call last):
  File "nlp-parser/linear.py", line 171, in <module>
    main()
  File "nlp-parser/linear.py", line 101, in main
    ssvm.fit(X_train, y_train)
  File "/opt/conda/lib/python3.8/site-packages/pystruct-0.3.2-py3.8-linux-x86_64.egg/pystruct/learners/frankwolfe_ssvm.py", line 299, in fit
    self._frank_wolfe_bc(X, Y)
  File "/opt/conda/lib/python3.8/site-packages/pystruct-0.3.2-py3.8-linux-x86_64.egg/pystruct/learners/frankwolfe_ssvm.py", line 223, in _frank_wolfe_bc
    y_hat, delta_joint_feature, slack, loss = find_constraint(self.model, x, y, w)
  File "/opt/conda/lib/python3.8/site-packages/pystruct-0.3.2-py3.8-linux-x86_64.egg/pystruct/utils/inference.py", line 65, in find_constraint
    y_hat = model.loss_augmented_inference(x, y, w, relaxed=relaxed)
  File "/opt/conda/lib/python3.8/site-packages/pystruct-0.3.2-py3.8-linux-x86_64.egg/pystruct/models/crf.py", line 116, in loss_augmented_inference
    return inference_dispatch(unary_potentials, pairwise_potentials, edges,
  File "/opt/conda/lib/python3.8/site-packages/pystruct-0.3.2-py3.8-linux-x86_64.egg/pystruct/inference/inference_methods.py", line 118, in inference_dispatch
    return inference_max_product(unary_potentials, pairwise_potentials,
  File "/opt/conda/lib/python3.8/site-packages/pystruct-0.3.2-py3.8-linux-x86_64.egg/pystruct/inference/maxprod.py", line 50, in inference_max_product
    from ._viterbi import viterbi
  File "__init__.pxd", line 178, in init pystruct.inference._viterbi (pystruct/inference/_viterbi.c:3970)
ValueError: numpy.ndarray has the wrong size, try recompiling
Makefile:65: recipe for target 'dccplineartrain' failed
make: *** [dccplineartrain] Error 1
```

I guess it's because of a version conflict with some python libraries. Below is my pip3 list:
```
root@dose:/workspace/rfcnlp# pip3 list
Package                Version
---------------------- -------------------
ad3                    2.2.1
allennlp               2.0.0
allennlp-models        2.0.0
backcall               0.2.0
beautifulsoup4         4.9.3
blis                   0.4.1
boto3                  1.34.15
botocore               1.34.15
brotlipy               0.7.0
catalogue              1.0.2
certifi                2020.12.5
cffi                   1.14.3
chardet                3.0.4
click                  8.1.7
conda                  4.9.2
conda-build            3.21.4
conda-package-handling 1.7.2
conllu                 4.3
contourpy              1.1.1
cryptography           3.2.1
cvxopt                 1.3.2
cycler                 0.12.1
cymem                  2.0.8
Cython                 3.0.7
decorator              4.4.2
deepwalk               1.0.3
dnspython              2.1.0
en-core-web-sm         2.2.5
exceptiongroup         1.2.0
filelock               3.0.12
fonttools              4.47.0
ftfy                   6.1.3
future                 0.18.3
futures                3.0.5
gensim                 4.3.2
glob2                  0.7
graphviz               0.20.1
h5py                   3.10.0
idna                   2.10
importlib-resources    6.1.1
iniconfig              2.0.0
ipython                7.19.0
ipython-genutils       0.2.0
jedi                   0.17.2
Jinja2                 2.11.2
jmespath               1.0.1
joblib                 1.3.2
jsonnet                0.20.0
jsonpickle             3.0.2
kiwisolver             1.4.5
korg                   0.1.0
Levenshtein            0.23.0
libarchive-c           2.9
lmdb                   1.4.1
lxml                   5.1.0
MarkupSafe             1.1.1
matplotlib             3.7.4
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
more-itertools         10.2.0
murmurhash             1.0.10
networkx               3.1
nltk                   3.6.5
numpy                  1.21.2
olefile                0.46
overrides              3.1.0
packaging              23.2
pandas                 2.0.3
parso                  0.7.0
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.1.0
pip                    23.3.2
pkginfo                1.7.0
plac                   1.1.3
pluggy                 1.3.0
preshed                3.0.9
prompt-toolkit         3.0.8
protobuf               4.25.1
psutil                 5.7.2
ptyprocess             0.7.0
py-rouge               1.1
pycosat                0.6.3
pycparser              2.20
Pygments               2.7.4
pyOpenSSL              19.1.0
pyparsing              3.1.1
PySocks                1.7.1
pystruct               0.3.2
pytest                 7.4.4
python-dateutil        2.8.2
python-etcd            0.4.5
python-Levenshtein     0.23.0
pytz                   2020.5
PyYAML                 5.3.1
rapidfuzz              3.6.1
regex                  2023.12.25
requests               2.24.0
ruamel_yaml            0.15.87
s3transfer             0.10.0
sacremoses             0.1.1
scikit-learn           1.0
scipy                  1.10.0
sentencepiece          0.1.99
setuptools             50.3.1.post20201107
six                    1.15.0
smart-open             6.4.0
soupsieve              2.1
spacy                  2.2.4
spacy-legacy           3.0.8
srsly                  1.0.7
tabulate               0.9.0
tensorboardX           2.6.2.2
thinc                  7.4.0
threadpoolctl          3.2.0
tokenizers             0.9.4
tomli                  2.0.1
torch                  1.7.1
torchelastic           0.2.1
torchvision            0.8.2
tqdm                   4.62.3
traitlets              5.0.5
transformers           4.2.2
transitions            0.9.0
typing-extensions      3.7.4.3
tzdata                 2023.4
urllib3                1.25.11
wasabi                 0.10.1
wcwidth                0.2.13
wheel                  0.35.1
word2number            1.1
zipp                   3.17.0
```
It seems that the numpy version was automatically upgraded to 1.24.4 during the docker build process. But the numpy version in the Dockerfile is 1.17.4. I guess it is because the version of pystruct or other libraries has been upgraded, causing the version of numpy to be upgraded. So I rolled back the numpy version to 1.21.2. Is there any problem with the library version in my pip3 list? Can you share your pip list?

**Comment by hugo0819** [comment]
I faced the same issues, did you deal with it ?
